"""Weapon category helpers for challenge and usage tracking."""

WEAPON_CATEGORIES = [
    "assault_rifle",
    "smg",
    "lmg",
    "pistol",
    "shotgun",
    "sniper",
    "launcher",
    "special",
    "melee",
    "explosive",
    "other",
]

WEAPON_CATEGORY_LABELS = {
    "assault_rifle": "Assault Rifle",
    "smg": "Submachine Gun",
    "lmg": "LMG",
    "pistol": "Pistol",
    "shotgun": "Shotgun",
    "sniper": "Sniper",
    "launcher": "Launcher",
    "special": "Special / Wonder Weapon",
    "melee": "Melee",
    "explosive": "Explosive",
    "other": "Other",
}

WEAPON_CATEGORY_PREFIXES = {
    "ar_": "assault_rifle",
    "smg_": "smg",
    "lmg_": "lmg",
    "pistol_": "pistol",
    "shotgun_": "shotgun",
    "sniper_": "sniper",
    "launcher_": "launcher",
    "special_": "special",
    "hero_": "special",
    "staff_": "special",
    "melee_": "melee",
    "knife_": "melee",
}

WEAPON_CATEGORY_TOKENS = {
    "_ar_": "assault_rifle",
    "_smg_": "smg",
    "_lmg_": "lmg",
    "_pistol_": "pistol",
    "_shotgun_": "shotgun",
    "_sniper_": "sniper",
    "_launcher_": "launcher",
    "_melee_": "melee",
}

CATEGORY_VARIANT_SUFFIXES = {
    "ar",
    "assault",
    "assault_rifle",
    "smg",
    "lmg",
    "pistol",
    "shotgun",
    "sniper",
    "launcher",
    "melee",
    "special",
}

WONDER_WEAPON_KEYWORDS = {
    "apothicon",
    "baby_gun",
    "blundergat",
    "dg4",
    "gersch",
    "ray_gun",
    "raygun",
    "scavenger",
    "servant",
    "staff_fire",
    "staff_ice",
    "staff_lightning",
    "staff_wind",
    "staff_air",
    "staff_water",
    "sliquifier",
    "thundergun",
    "vr11",
    "wave_gun",
    "wintershowl",
    "wunderwaffe",
    "wonderwaffe",
}

CONSOLE_NAME_CATEGORY_OVERRIDES = {
    "cso2_ak47flash": "assault_rifle",
    "h1_p90": "smg",
    "h1_g3": "assault_rifle",
    "h1_g36c": "assault_rifle",
    "h1_m4_carbine": "assault_rifle",
    "h1_m16a4": "assault_rifle",
    "h1_m1014": "shotgun",
    "h1_m21": "sniper",
    "h1_m40a3": "sniper",
    "h1_mini_uzi": "smg",
    "h1_mac10": "smg",
    "h1_ak74u": "smg",
    "h1_beretta_m9": "pistol",
    "h1_usp45": "pistol",
    "h1_rem700": "sniper",
    "h1_lynx_cq300": "sniper",
    "h1_pkm": "lmg",
    "h1_minigun": "lmg",
    "h1_kamchatka12": "shotgun",
    "h1_xmlar": "assault_rifle",
    "h1_bos14": "assault_rifle",
    "h1_pk_psd9": "smg",
    "hr_fuelrod": "launcher",
    "h1_rpg7": "launcher",
    "iw4_ump45": "smg",
    "iw5_aa12": "shotgun",
    "iw5_44magnum": "pistol",
    "iw5_g36c": "assault_rifle",
    "iw5_mp5": "smg",
    "iw5_striker": "shotgun",
    "iw5_usas12": "shotgun",
    "iw6_bizon": "smg",
    "iw6_ia2": "assault_rifle",
    "iw6_ak12": "assault_rifle",
    "iw6_honeybadger": "assault_rifle",
    "iw6_kastet": "launcher",
    "iw6_m27_iar": "lmg",
    "iw6_mk32": "launcher",
    "iw6_mr28": "sniper",
    "iw6_panzerfaust3": "launcher",
    "iw6_sc2010": "assault_rifle",
    "iw6_venomx": "special",
    "iw6_vepr": "smg",
    "iw6_p226": "pistol",
    "iw8_50gs": "pistol",
    "iw8_357": "pistol",
    "iw8_asval": "assault_rifle",
    "iw8_bizon": "smg",
    "iw8_g36k": "assault_rifle",
    "iw8_grau556": "assault_rifle",
    "iw8_holger26": "lmg",
    "iw8_m13": "assault_rifle",
    "iw8_m16a4": "assault_rifle",
    "iw8_m4a1": "assault_rifle",
    "iw8_m4a1_classic": "assault_rifle",
    "iw8_oden": "assault_rifle",
    "iw8_origin12": "shotgun",
    "iw8_p90": "smg",
    "iw8_rpg7": "launcher",
    "iw8_sig550": "assault_rifle",
    "iw8_sks": "sniper",
    "iw8_vintorez": "sniper",
    "iw8_vks": "sniper",
    "s1_ae4": "assault_rifle",
    "s2_grease_gun": "smg",
    "s2_delisle": "sniper",
    "s2_enfieldno2": "pistol",
    "s2_fg42": "assault_rifle",
    "s2_m1903": "sniper",
    "s2_m1a1carbine": "assault_rifle",
    "s2_m1garand": "assault_rifle",
    "s2_m1919": "lmg",
    "s2_m1928": "smg",
    "s2_mp40": "smg",
    "s2_ppsh41_drum": "smg",
    "s2_waffe28": "smg",
    "s2_win21": "shotgun",
    "s4_1911": "pistol",
    "s4_automaton": "assault_rifle",
    "s4_double_barrel": "shotgun",
    "s4_dp27": "lmg",
    "s4_g43": "assault_rifle",
    "s4_itra_burst": "assault_rifle",
    "s4_lee_enfield_scope": "sniper",
    "s4_m1bazooka": "launcher",
    "s4_mp40": "smg",
    "s4_ppsh41_base": "smg",
    "s4_ppsh41_drum": "smg",
    "s4_ratt": "pistol",
    "s4_sten": "smg",
    "s4_tesla_gun": "special",
    "s4_type99_irons": "sniper",
    "s4_type99_scope": "sniper",
    "s4_volkstg": "assault_rifle",
    "t5_ak74u": "smg",
    "t5_famas": "assault_rifle",
    "t5_galil": "assault_rifle",
    "t5_asp": "pistol",
    "t5_aug": "assault_rifle",
    "t5_m16a1": "assault_rifle",
    "t5_makarov": "pistol",
    "t5_minigun": "lmg",
    "t5_m202": "launcher",
    "t5_mpl": "smg",
    "t6_peacekeeper": "assault_rifle",
    "t6_stinger": "launcher",
    "t6_type25": "assault_rifle",
    "t6_war_machine": "launcher",
    "t6_xpr50": "sniper",
    "t6_m16a1": "assault_rifle",
    "t6_mg0815": "lmg",
    "t6_vector_k10": "smg",
    "t6_xl_m14": "assault_rifle",
    "t6_zombie_tomahawk": "special",
    "t7_idgun": "special",
    "t7_idgun_genesis": "special",
    "t8_abr223": "assault_rifle",
    "t8_auger_dmr": "assault_rifle",
    "t8_daemon3xb": "smg",
    "t8_escargot": "pistol",
    "t8_essex_m07": "assault_rifle",
    "t8_hades": "lmg",
    "t8_hellion_salvo": "launcher",
    "t8_hitchcock_m9": "pistol",
    "t8_icr7": "assault_rifle",
    "t8_gks": "smg",
    "t8_kn57": "assault_rifle",
    "t8_kap45": "pistol",
    "t8_m1897": "shotgun",
    "t8_maddox_rfb": "assault_rifle",
    "t8_mog12": "shotgun",
    "t8_mozu": "pistol",
    "t8_mx9": "smg",
    "t8_overkill": "shotgun",
    "t8_outlaw": "sniper",
    "t8_paladin_hb50": "sniper",
    "t8_rampage": "shotgun",
    "t8_rk7": "pistol",
    "t8_saug9mm": "smg",
    "t8_sdm": "sniper",
    "t8_sg12": "shotgun",
    "t8_spitfire": "smg",
    "t8_swat_rft": "assault_rifle",
    "t8_switchblade_x9": "smg",
    "t8_swordfish": "assault_rifle",
    "t8_titan": "lmg",
    "t8_vapr_xkg": "assault_rifle",
    "t8_vendetta": "sniper",
    "t8_welling": "pistol",
    "t8_zweihander": "lmg",
    "t9_1911": "pistol",
    "t9_410ironhide": "shotgun",
    "t9_ak47": "assault_rifle",
    "t9_aug": "assault_rifle",
    "t9_bullfrog": "smg",
    "t9_crossbow": "special",
    "t9_crossbow_skull": "special",
    "t9_gallo_sa12": "shotgun",
    "t9_grav": "assault_rifle",
    "t9_krig6": "assault_rifle",
    "t9_lw3_tundra": "sniper",
    "t9_m14classic": "assault_rifle",
    "t9_m16": "assault_rifle",
    "t9_mac10": "smg",
    "t9_m60": "lmg",
    "t9_nail_gun": "special",
    "t9_pelington703": "sniper",
    "t9_qbz83": "assault_rifle",
    "t9_rpg7": "launcher",
    "t9_streetsweeper": "shotgun",
    "t9_tec9": "smg",
    "t9_xm4": "assault_rifle",
    "t4_ppsh": "smg",
    "t4_ppsh41_drum": "smg",
    "t4r_ppsh": "smg",
    "bf2_dlt19": "lmg",
    "bf2_dlt19x": "sniper",
    "bf2_e11": "assault_rifle",
    "bf2_e5": "assault_rifle",
    "bf2_ec17": "pistol",
    "bf2_t21": "lmg",
    "bf2_t21b": "sniper",
    "bf2_tl50": "lmg",
    "e11_blaster": "assault_rifle",
    "lightsaber_revan": "melee",
    "sw_lightsaber_obi_wan": "melee",
    "knife": "melee",
    "bowie_knife": "melee",
    "melee_jug": "melee",
    "melee_scythe": "melee",
    "melee_seasonal_pipe": "melee",
    "t9_me_knife_russian": "melee",
    "t9_me_wakizashi": "melee",
    "tesla_gun": "special",
    "octobomb": "special",
    "beacon": "special",
    "idgun_0": "special",
    "idgun_1": "special",
    "idgun_3": "special",
    "idgun_upgraded_0": "special",
    "t7_quantum_bomb": "special",
    "iw5_cm901": "assault_rifle",
    "iw7_atlas": "lmg",
    "iw7_auger": "lmg",
    "iw7_banshee": "shotgun",
    "iw7_dcm8": "shotgun",
    "iw7_dmr1": "sniper",
    "iw7_ebr800_sniper": "sniper",
    "iw7_emc": "pistol",
    "iw7_erad": "smg",
    "iw7_fhr40": "smg",
    "iw7_grail": "assault_rifle",
    "iw7_hailstorm": "pistol",
    "iw7_hornet": "pistol",
    "iw7_howitzer": "launcher",
    "iw7_hvr": "smg",
    "iw7_karma45": "smg",
    "iw7_kbar32": "assault_rifle",
    "iw7_kbs_longbow": "sniper",
    "iw7_kendall44": "pistol",
    "iw7_m1": "sniper",
    "iw7_mactav45": "smg",
    "iw7_m2187": "shotgun",
    "iw7_mauler": "lmg",
    "iw7_nv4": "assault_rifle",
    "iw7_oni": "pistol",
    "iw7_osa": "assault_rifle",
    "iw7_proteus": "sniper",
    "iw7_r3k": "assault_rifle",
    "iw7_rack9": "shotgun",
    "iw7_raijin_emx": "smg",
    "iw7_raw": "lmg",
    "iw7_reaver": "shotgun",
    "iw7_rpr_evo": "smg",
    "iw7_rvn": "assault_rifle",
    "iw7_sravage": "shotgun",
    "iw7_stallion_44": "pistol",
    "iw7_tf141": "sniper",
    "iw7_titan": "lmg",
    "iw7_trek50": "sniper",
    "iw7_trencher": "smg",
    "iw7_type2": "assault_rifle",
    "iw7_volk": "assault_rifle",
    "iw7_widowmaker": "sniper",
    "zod_riotshield": "special",
    "zombie_bgb_grab": "special",
    "big_daddy_drill_wonder_weapon": "special",
    "sw_lightsaber": "melee",
    "bloodhound": "pistol",
    "vector": "smg",
    "frag_grenade": "explosive",
    "m17_frag_grenade": "explosive",
    "frag_grenade_potato_masher": "explosive",
    "cymbal_monkey": "explosive",
}

CONSOLE_NAME_CATEGORY_OVERRIDES.update({
    "bouncingbetty": "explosive",
    "incendiary_grenade": "explosive",
    "spx_brazen_bull_shield": "special",
    "spx_origins_shield": "special",
    "spx_spectral_shield": "special",
    "spx_vine_shield": "special",
    "spx_zombie_shield": "special",
    "zombie_beast_grapple_dwr": "special",
    "zombie_bgb_use": "special",
    "elemental_bow": "special",
    "elemental_bow_rune_prison": "special",
    "elemental_bow_storm": "special",
    "elemental_bow_wolf_howl": "special",
    "wrath of the ancients": "special",
    "microwavegundw": "special",
    "raymachine": "special",
    "m2_flamethrower": "special",
    "wpn_custom_spoon_01": "melee",
    "sickle_knife": "melee",
    "m1911": "pistol",
    "makarov": "pistol",
    "maxim9": "pistol",
    "renetti": "pistol",
    "m1887": "shotgun",
    "mossberg": "shotgun",
    "tac1928": "smg",
    "cso2qsz92": "pistol",
    "aw_irons": "pistol",
    "bo1_bouncingbetty": "explosive",
    "cesarw_brevolver": "pistol",
    "cesarw_puntgun_explosive": "explosive",
    "iw7_xeon": "assault_rifle",
    "misc_barehands": "melee",
    "season_2_h1_m40_v2": "sniper",
    "waw_ppsh": "smg",
    "bo3_axe": "melee",
    "bo3_bat": "melee",
    "bo3_butterfly_knife": "melee",
    "bo3_chainsaw_knuckles": "melee",
    "bo3_galil": "assault_rifle",
    "bo3_improvised": "melee",
    "bo3_mark2": "special",
    "bo3_mp40": "smg",
    "bo3_olympia": "shotgun",
    "mw6_basb": "assault_rifle",
    "mw6_m4": "assault_rifle",
    "mw6_rival9": "smg",
    "mw6_x12": "pistol",
    "apex_alternator": "smg",
    "apex_b3wing": "pistol",
    "apex_beam_rifle": "assault_rifle",
    "apex_flatline": "assault_rifle",
    "apex_hemlok": "assault_rifle",
    "apex_lstar": "lmg",
    "apex_mastiff": "shotgun",
    "apex_mozambique": "shotgun",
    "apex_p2011": "pistol",
    "apex_p2011_auto": "pistol",
    "apex_prowler": "smg",
    "apex_r301": "assault_rifle",
    "apex_r97": "smg",
    "apex_tripletake": "sniper",
    "apex_w1128": "shotgun",
    "h1_44magnum": "pistol",
    "h1_bered_mk8": "pistol",
    "h1_beredmk8": "pistol",
    "h1_br9": "pistol",
    "h1_fang45": "smg",
    "h1_kam12": "shotgun",
    "h1_lynxcq300": "assault_rifle",
    "h1_m1911": "pistol",
    "h1_m249": "lmg",
    "h1_m4carbine": "assault_rifle",
    "h1_m60e4": "lmg",
    "h1_m82a1": "sniper",
    "h1_m9": "pistol",
    "h1_mp44": "assault_rifle",
    "h1_pkpsd9": "smg",
    "h1_prokolot": "pistol",
    "h1_ranger": "shotgun",
    "h1_ranger_rdw": "shotgun",
    "h1_stac": "sniper",
    "h1_win1200": "shotgun",
    "h2_44magnum": "pistol",
    "h2_aa12": "shotgun",
    "h2_acr": "assault_rifle",
    "h2_at4": "launcher",
    "h2_aug_hbar": "lmg",
    "h2_deagle": "pistol",
    "h2_f2000": "assault_rifle",
    "h2_fal": "assault_rifle",
    "h2_famas": "assault_rifle",
    "h2_g18": "pistol",
    "h2_intervention": "sniper",
    "h2_l86_lsw": "lmg",
    "h2_m1014": "shotgun",
    "h2_m14ebr": "sniper",
    "h2_m16a4": "assault_rifle",
    "h2_m1911": "pistol",
    "h2_m240": "lmg",
    "h2_m4a1": "assault_rifle",
    "h2_m9": "pistol",
    "h2_m93raffica": "pistol",
    "h2_mg4": "lmg",
    "h2_mini_uzi": "smg",
    "h2_model1887": "shotgun",
    "h2_mp5k": "smg",
    "h2_p90": "smg",
    "h2_pp2000": "smg",
    "h2_ranger": "shotgun",
    "h2_rpg7": "launcher",
    "h2_spas12": "shotgun",
    "h2_striker": "shotgun",
    "h2_tar21": "assault_rifle",
    "h2_thumper": "launcher",
    "h2_tmp": "smg",
    "h2_ump45": "smg",
    "h2_usp45": "pistol",
    "h2_vector": "smg",
    "h2_win1200": "shotgun",
    "iw_ar57": "assault_rifle",
    "iw_arx160": "assault_rifle",
    "iw_dcm8": "shotgun",
    "iw_devastator": "shotgun",
    "iw_drm1": "sniper",
    "iw_eak47": "assault_rifle",
    "iw_emc": "pistol",
    "iw_erad": "smg",
    "iw_fhr40": "smg",
    "iw_fmg": "assault_rifle",
    "iw_hvr": "smg",
    "iw_kbcbr": "smg",
    "iw_kbsniper": "sniper",
    "iw_m1": "sniper",
    "iw_m4": "assault_rifle",
    "iw_m8": "sniper",
    "iw_mauler": "lmg",
    "iw_rack9": "shotgun",
    "iw_raw": "lmg",
    "iw_revolver": "pistol",
    "iw_rvn": "assault_rifle",
    "iw_sonicshotgun": "shotgun",
    "iw_ump": "smg",
    "iw3_ak47": "assault_rifle",
    "iw3_ak74u": "smg",
    "iw3_g3": "assault_rifle",
    "iw3_g36c": "assault_rifle",
    "iw3_m1014": "shotgun",
    "iw3_m16a4": "assault_rifle",
    "iw3_m1911": "pistol",
    "iw3_m21": "sniper",
    "iw3_m249": "lmg",
    "iw3_m40a3": "sniper",
    "iw3_m4a1": "assault_rifle",
    "iw3_m60e4": "lmg",
    "iw3_m9": "pistol",
    "iw3_mini_uzi": "smg",
    "iw3_mp44": "assault_rifle",
    "iw3_mp5sd": "smg",
    "iw3_p90": "smg",
    "iw3_rem700": "sniper",
    "iw3_rpd": "lmg",
    "iw3_rpg7": "launcher",
    "iw3_skorpion": "smg",
    "iw3_usp45": "pistol",
    "iw3_win1200": "shotgun",
    "iw4_44magnum": "pistol",
    "iw4_aa12": "shotgun",
    "iw4_acr": "assault_rifle",
    "iw4_at4": "launcher",
    "iw4_aug_hbar": "lmg",
    "iw4_f2000": "assault_rifle",
    "iw4_famas": "assault_rifle",
    "iw4_g18": "pistol",
    "iw4_intervention": "sniper",
    "iw4_l86_lsw": "lmg",
    "iw4_m1014": "shotgun",
    "iw4_m14ebr": "sniper",
    "iw4_m16a4": "assault_rifle",
    "iw4_m240": "lmg",
    "iw4_m4a1": "assault_rifle",
    "iw4_m9": "pistol",
    "iw4_m93r": "pistol",
    "iw4_mg4": "lmg",
    "iw4_mini_uzi": "smg",
    "iw4_model1887": "shotgun",
    "iw4_p90": "smg",
    "iw4_pp2000": "smg",
    "iw4_ranger": "shotgun",
    "iw4_rpg7": "launcher",
    "iw4_striker": "shotgun",
    "iw4_tar21": "assault_rifle",
    "iw4_thumper": "launcher",
    "iw4_tmp": "smg",
    "iw4_usp45": "pistol",
    "iw4_vector": "smg",
    "iw5_ak74u": "smg",
    "iw5_fad": "assault_rifle",
    "iw5_fiveseven": "pistol",
    "iw5_m16a4": "assault_rifle",
    "iw5_m60e4": "lmg",
    "iw5_mg36": "lmg",
    "iw5_mk14": "assault_rifle",
    "iw5_mk46": "lmg",
    "iw5_model1887": "shotgun",
    "iw5_mp9": "smg",
    "iw5_msr": "sniper",
    "iw5_p90": "smg",
    "iw5_p99": "pistol",
    "iw5_pkp": "lmg",
    "iw5_pm9": "smg",
    "iw5_pp90m1": "smg",
    "iw5_rsass": "sniper",
    "iw5_scarl": "assault_rifle",
    "iw5_type95": "assault_rifle",
    "iw5_ump45": "smg",
    "iw6_44magnum": "pistol",
    "iw6_ameli": "lmg",
    "iw6_aps": "assault_rifle",
    "iw6_arx160": "assault_rifle",
    "iw6_bulldog": "shotgun",
    "iw6_cbjms": "smg",
    "iw6_chain_saw": "lmg",
    "iw6_fad": "assault_rifle",
    "iw6_fp6": "shotgun",
    "iw6_k7": "smg",
    "iw6_l115": "sniper",
    "iw6_lynx": "sniper",
    "iw6_m9a1": "pistol",
    "iw6_maaws": "launcher",
    "iw6_maverick": "assault_rifle",
    "iw6_maverick_a2": "sniper",
    "iw6_minigun": "lmg",
    "iw6_mk14_ebr": "sniper",
    "iw6_mp443": "pistol",
    "iw6_msbs": "assault_rifle",
    "iw6_mtarx": "assault_rifle",
    "iw6_mtarx2": "assault_rifle",
    "iw6_mts255": "shotgun",
    "iw6_pdw": "smg",
    "iw6_r5rgp": "assault_rifle",
    "iw6_sa805": "assault_rifle",
    "iw6_svu": "sniper",
    "iw6_tac12": "shotgun",
    "iw6_usr": "sniper",
    "iw6_vector_crb": "smg",
    "iw6_vks": "sniper",
    "iw8_1911": "pistol",
    "iw8_725": "shotgun",
    "iw8_ak74u": "smg",
    "iw8_an94": "assault_rifle",
    "iw8_ax50": "sniper",
    "iw8_beretta93r": "pistol",
    "iw8_bruenmk9": "lmg",
    "iw8_chainsaw": "lmg",
    "iw8_cr56": "assault_rifle",
    "iw8_cx9": "smg",
    "iw8_ebr14": "sniper",
    "iw8_fennec": "smg",
    "iw8_finn": "lmg",
    "iw8_fr556": "assault_rifle",
    "iw8_hdr": "sniper",
    "iw8_iso": "smg",
    "iw8_jak12": "shotgun",
    "iw8_kar98k_scope": "sniper",
    "iw8_kilo141": "assault_rifle",
    "iw8_m19": "pistol",
    "iw8_m21ebr": "sniper",
    "iw8_m91": "lmg",
    "iw8_makarovpb": "pistol",
    "iw8_mg34": "lmg",
    "iw8_minigun": "lmg",
    "iw8_mk2carbine": "sniper",
    "iw8_model680": "shotgun",
    "iw8_mp5sd": "smg",
    "iw8_pkm": "lmg",
    "iw8_r90": "shotgun",
    "iw8_raalmg": "lmg",
    "iw8_ram7": "assault_rifle",
    "iw8_renetti": "pistol",
    "iw8_rpk": "lmg",
    "iw8_rytecamr": "sniper",
    "iw8_sa87": "lmg",
    "iw8_scar17s": "assault_rifle",
    "iw8_scar_pdw": "assault_rifle",
    "iw8_scar_tpr": "assault_rifle",
    "iw8_spr208_irons": "sniper",
    "iw8_spr208_scope": "sniper",
    "iw8_stechkin_apb": "pistol",
    "iw8_stechkin_aps": "pistol",
    "iw8_striker45": "smg",
    "iw8_sykov": "pistol",
    "iw8_vlkrogue": "shotgun",
    "iw8_x16": "pistol",
    "s1_asm1": "smg",
    "s1_atlas45": "pistol",
    "s1_bal27": "assault_rifle",
    "s1_bulldog": "shotgun",
    "s1_cel3": "shotgun",
    "s1_m1_irons": "assault_rifle",
    "s1_mdl": "launcher",
    "s1_mk14": "assault_rifle",
    "s1_mors": "sniper",
    "s1_sn6": "smg",
    "s2_as44": "assault_rifle",
    "s2_austen": "smg",
    "s2_avs36": "assault_rifle",
    "s2_bazooka": "launcher",
    "s2_bechowiec": "smg",
    "s2_beretta38": "smg",
    "s2_beretta_m1938a": "smg",
    "s2_blunderbuss": "shotgun",
    "s2_blyskawica": "smg",
    "s2_breda1935": "assault_rifle",
    "s2_breda30": "lmg",
    "s2_breda_m1930": "lmg",
    "s2_bredapg35": "assault_rifle",
    "s2_bren": "lmg",
    "s2_chatellerault": "lmg",
    "s2_de_lisle": "sniper",
    "s2_emp44": "smg",
    "s2_enfield_no2": "pistol",
    "s2_erma_emp": "smg",
    "s2_fedorov": "assault_rifle",
    "s2_grossfuss_stg": "assault_rifle",
    "s2_kbsp38m": "assault_rifle",
    "s2_kbsp_1938": "assault_rifle",
    "s2_kgm21": "assault_rifle",
    "s2_lad": "lmg",
    "s2_lee_enfield": "sniper",
    "s2_lewis": "lmg",
    "s2_luger": "pistol",
    "s2_m1927": "smg",
    "s2_m1941": "assault_rifle",
    "s2_m2carbine": "assault_rifle",
    "s2_m2hyde": "smg",
    "s2_m30": "shotgun",
    "s2_m712": "pistol",
    "s2_mas36": "sniper",
    "s2_mas38": "smg",
    "s2_mg15": "lmg",
    "s2_mg81": "lmg",
    "s2_model21": "shotgun",
    "s2_mosin": "sniper",
    "s2_nz41": "assault_rifle",
    "s2_p38": "pistol",
    "s2_ppsh41_base": "smg",
    "s2_ptrs41": "sniper",
    "s2_reichs": "pistol",
    "s2_ribeyrolles": "assault_rifle",
    "s2_sdk": "sniper",
    "s2_sten": "smg",
    "s2_sterling": "smg",
    "s2_type2": "smg",
    "s2_type38": "sniper",
    "s2_type5": "assault_rifle",
    "s2_vmg1927": "lmg",
    "s2_volkstg": "assault_rifle",
    "s2_walther_auto": "shotgun",
    "s2_wimmersperg": "assault_rifle",
    "s2_win1897": "shotgun",
    "s2_win_1897": "shotgun",
    "s2_zk383": "smg",
    "s4_einhorn": "shotgun",
    "s4_gorenko_rifle": "sniper",
    "s4_kar98k_scope": "sniper",
    "s4_mg42": "lmg",
    "s4_mp41": "smg",
    "s4_pps43": "smg",
    "s4_stg44": "assault_rifle",
    "s4_thompsonm1a1": "smg",
    "t4_357": "pistol",
    "t4_357_scope": "pistol",
    "t4_357magnum": "pistol",
    "t4_bar_bipod": "lmg",
    "t4_bazooka": "launcher",
    "t4_db": "shotgun",
    "t4_db_saw": "shotgun",
    "t4_dp28": "lmg",
    "t4_fg42": "assault_rifle",
    "t4_kar98k_scope": "sniper",
    "t4_m1897": "shotgun",
    "t4_m1897_slug": "shotgun",
    "t4_m1911": "pistol",
    "t4_m1911_hp": "pistol",
    "t4_m1919": "lmg",
    "t4_m1919_bipod": "lmg",
    "t4_m1_scope": "sniper",
    "t4_m1c": "sniper",
    "t4_m1carbine": "assault_rifle",
    "t4_m1garand_rg": "assault_rifle",
    "t4_mg42": "lmg",
    "t4_mg42_bipod": "lmg",
    "t4_mosin": "sniper",
    "t4_mosin_hp": "sniper",
    "t4_mosin_irons": "sniper",
    "t4_mosin_scope": "sniper",
    "t4_mp40_bigammo": "smg",
    "t4_nambu": "pistol",
    "t4_nambu_hp": "pistol",
    "t4_p38": "pistol",
    "t4_p38_hp": "pistol",
    "t4_ppsh41_base": "smg",
    "t4_ptrs": "sniper",
    "t4_ptrs41": "sniper",
    "t4_ptrs_iron": "sniper",
    "t4_spring": "sniper",
    "t4_spring_hp": "sniper",
    "t4_spring_scope": "sniper",
    "t4_springfield_irons": "sniper",
    "t4_springfield_scope": "sniper",
    "t4_svt_scope": "assault_rifle",
    "t4_thompson": "smg",
    "t4_thompson_base": "smg",
    "t4_thompson_drum": "smg",
    "t4_tokarev": "pistol",
    "t4_tokarev_hp": "pistol",
    "t4_tt33": "pistol",
    "t4_type100": "smg",
    "t4_type99": "sniper",
    "t4_type99r": "sniper",
    "t4_type99r_hp": "sniper",
    "t4_type99r_scope": "sniper",
    "t5_ak47": "assault_rifle",
    "t5_commando": "assault_rifle",
    "t5_enfield": "assault_rifle",
    "t5_g11": "assault_rifle",
    "t5_m1911": "pistol",
    "t5_m60e3": "lmg",
    "t5_mp40": "smg",
    "t5_mp5k": "smg",
    "t5_python": "pistol",
    "t5_rpk": "lmg",
    "t5_spas12": "shotgun",
    "t5_stoner63": "lmg",
    "t5_strela3": "launcher",
    "t6_ak74u": "smg",
    "t6_b23r": "pistol",
    "t6_dragunov": "sniper",
    "t6_ksg": "shotgun",
    "t6_m1927": "smg",
    "t6_m82a1": "sniper",
    "t6_mk48": "lmg",
    "t6_mm1": "launcher",
    "t6_mp40": "smg",
    "t6_mp5": "smg",
    "t6_mp7": "smg",
    "t6_olympia": "shotgun",
    "t6_xl_death_machine": "lmg",
    "t6_xl_m1927": "smg",
    "t6_xl_uzi": "smg",
    "t8_cordite": "smg",
    "t8_grav": "assault_rifle",
    "t8_koshka": "sniper",
    "t8_magmagat": "special",
    "t8_m1927": "smg",
    "t8_rampart17": "assault_rifle",
    "t8_strife": "pistol",
    "t8_vkm750": "lmg",
    "t9_ak74u": "smg",
    "t9_ballistic_knife": "special",
    "t9_diamatti": "pistol",
    "t9_me_scythe": "melee",
    "t9_pi_1911_classic": "pistol",
    "t9_pi_revolver_rdw": "pistol",
    "t9_ppsh41_base": "smg",
    "t9_ppsh41_drum": "smg",
    "t9_sp_ballistic_knife": "special",
    "t9_sp_crossbow": "special",
    "t9_stoner63": "lmg",
    "t9_swiss_k31_irons": "sniper",
    "t9_swiss_k31_scope": "sniper",
    "t9_tr_powerburst": "assault_rifle",
    "t9_type63": "assault_rifle",
    "t9_zrg20mm": "sniper",
    "t10_pi_pyork": "pistol",
})

DISPLAY_NAME_CATEGORY_OVERRIDES = {
    "3 line rifle": "sniper",
    "ak47": "assault_rifle",
    "ak 47": "assault_rifle",
    "ak74u": "smg",
    "an 94": "assault_rifle",
    "as44": "assault_rifle",
    "ballista": "sniper",
    "bar": "assault_rifle",
    "barrett m82a1": "sniper",
    "b23r": "pistol",
    "browning hp": "pistol",
    "china lake": "launcher",
    "chicom cqb": "smg",
    "colt m16a1": "assault_rifle",
    "combat shotgun": "shotgun",
    "cz75": "pistol",
    "cz75 dual wield": "pistol",
    "death machine": "lmg",
    "desert eagle": "pistol",
    "dragunov": "sniper",
    "dsr 50": "sniper",
    "einhorn revolving": "shotgun",
    "enfield": "assault_rifle",
    "executioner": "pistol",
    "fal": "assault_rifle",
    "fal osw": "assault_rifle",
    "five seven": "pistol",
    "five seven dual wield": "pistol",
    "fn fal": "assault_rifle",
    "g11": "assault_rifle",
    "galil": "assault_rifle",
    "gewehr 43": "assault_rifle",
    "gorenko anti tank rifle": "sniper",
    "hamr": "lmg",
    "hk21": "lmg",
    "hs 10": "shotgun",
    "kap 40": "pistol",
    "kar98k": "sniper",
    "kiparis": "smg",
    "ks 23": "shotgun",
    "ksg": "shotgun",
    "l96a1": "sniper",
    "lsat": "lmg",
    "m1 garand": "assault_rifle",
    "m1a1 carbine": "assault_rifle",
    "m8a1": "assault_rifle",
    "m14": "assault_rifle",
    "m16a1": "assault_rifle",
    "m27": "assault_rifle",
    "m60": "lmg",
    "m60e3": "lmg",
    "m72 law": "launcher",
    "m1216": "shotgun",
    "m1911": "pistol",
    "m1927": "smg",
    "mac11": "smg",
    "mauser c96": "pistol",
    "mg 42": "lmg",
    "mg08 15": "lmg",
    "mk 48": "lmg",
    "mm1 grenade launcher": "launcher",
    "mp5": "smg",
    "mp5k": "smg",
    "mp7": "smg",
    "mp40": "smg",
    "mpl": "smg",
    "msmc": "smg",
    "mtar": "assault_rifle",
    "olympia": "shotgun",
    "panzerschreck": "launcher",
    "pdw 57": "smg",
    "peacekeeper": "assault_rifle",
    "pm63": "smg",
    "ppsh 41 w drum magazine": "smg",
    "psg1": "sniper",
    "python": "pistol",
    "qbb lsw": "lmg",
    "remington 870 mcs": "shotgun",
    "remington new model army": "pistol",
    "rpd": "lmg",
    "rpg": "launcher",
    "rpk": "lmg",
    "s12": "shotgun",
    "scar h": "assault_rifle",
    "skorpion": "smg",
    "skorpion evo": "smg",
    "smaw": "launcher",
    "smr": "assault_rifle",
    "spas 12": "shotgun",
    "spectre": "smg",
    "stakeout": "shotgun",
    "stg 44": "assault_rifle",
    "stg44": "assault_rifle",
    "stoner63": "lmg",
    "storm psr": "sniper",
    "stinger": "launcher",
    "svt 40": "assault_rifle",
    "svu as": "sniper",
    "swat 556": "assault_rifle",
    "tac 45": "pistol",
    "thompson m1a1": "smg",
    "titus 6": "launcher",
    "type 25": "assault_rifle",
    "type 100": "smg",
    "uzi": "smg",
    "wa2000": "sniper",
}


def normalise_weapon_category(value):
    text = str(value or "").strip().lower().replace(" ", "_").replace("-", "_")
    if "|" in text:
        text = text.split("|", 1)[0].strip("_ ")
    aliases = {
        "ar": "assault_rifle",
        "assault": "assault_rifle",
        "assault_rifles": "assault_rifle",
        "submachine_gun": "smg",
        "submachine_guns": "smg",
        "machine_pistol": "pistol",
        "wonder": "special",
        "wonder_weapon": "special",
        "wonder_weapons": "special",
        "special_weapon": "special",
        "special_weapons": "special",
        "knife": "melee",
        "unknown": "other",
        "misc": "other",
        "miscellaneous": "other",
    }
    text = aliases.get(text, text)
    return text if text in WEAPON_CATEGORIES else "other"


def get_weapon_category(console_name, display_name=""):
    name = str(console_name or "").strip().lower()
    display = str(display_name or "").strip().lower()
    combined = f"{name} {display}"

    for keyword in WONDER_WEAPON_KEYWORDS:
        if keyword in combined:
            return "special"

    for prefix, category in WEAPON_CATEGORY_PREFIXES.items():
        if name.startswith(prefix):
            return category

    lookup_name = name
    for suffix in ("_upgraded", "_up"):
        if lookup_name.endswith(suffix):
            lookup_name = lookup_name[:-len(suffix)]
            break

    if lookup_name in CONSOLE_NAME_CATEGORY_OVERRIDES:
        return CONSOLE_NAME_CATEGORY_OVERRIDES[lookup_name]
    for override, category in CONSOLE_NAME_CATEGORY_OVERRIDES.items():
        if lookup_name.startswith(f"{override}_"):
            variant_suffix = lookup_name[len(override) + 1:]
            if variant_suffix in CATEGORY_VARIANT_SUFFIXES:
                continue
            return category

    if lookup_name.startswith("gobblegun"):
        return "special"

    token_name = f"_{lookup_name}_"
    for token, category in WEAPON_CATEGORY_TOKENS.items():
        if token in token_name:
            return category

    normalised_display = "".join(ch if ch.isalnum() else " " for ch in display)
    normalised_display = " ".join(normalised_display.split())
    if normalised_display in DISPLAY_NAME_CATEGORY_OVERRIDES:
        return DISPLAY_NAME_CATEGORY_OVERRIDES[normalised_display]

    return "other"
